In [146]:
import numpy as numpy

SUPECIALCHAR = -100001

with open('../PatternText/pattern.txt', 'r') as f:
  P = np.array(list(map(int, f.read().splitlines())))
PLength = len(P)

predP = np.zeros(PLength, dtype=int)
pred = SUPECIALCHAR
for i in P.argsort():
  predP[i] = pred
  pred = i

SP = np.zeros(PLength, dtype=int)
for i in range(PLength):
  if(predP[i]==SUPECIALCHAR):
    SP[i] = predP[i]
  else:
    SP[i] = predP[i] - i

with open('../PatternText/text.txt', 'r') as f:
  T = np.array(list(map(int, f.read().splitlines())))
TLength = len(T)

Tsub = np.zeros((TLength-PLength+1, PLength), dtype=int)
for i in range(TLength-PLength+1):
  for j in range(PLength):
    Tsub[i][j] = T[i+j]

predT = np.zeros((TLength-PLength+1, PLength), dtype=int)

for i in range(TLength-PLength+1):
  pred = SUPECIALCHAR
  for j in Tsub[i].argsort():
    predT[i][j] = pred
    pred = i+j

ST = np.zeros((TLength-PLength+1, PLength), dtype=int)
for i in range(TLength-PLength+1):
  for j in range(PLength):
    if(predT[i][j]==SUPECIALCHAR):
      ST[i][j] = predT[i][j]
    else:
      ST[i][j] = predT[i][j] - (i+j)

with open('hammingAnswerK=1.txt', 'r') as f:
  correctIndex = np.array(list(map(int, f.read().splitlines())))

In [158]:
correctIndex

array([ 4551, 17574, 25769, 40603, 68144, 86765, 89163, 96996])

In [205]:
correct = 89163

In [206]:
a = P
b = T[correct:correct+PLength]
Sa = SP
Sb = ST[correct]
temp = Sa==Sb
d = []
for i in range(len(temp)):
    if(temp[i]) == False:
        d.append(i)
    if a[i]==100001 and b[i]==100001:
        d.append(i)
d = np.array(d)

In [207]:
a

array([1788, 7881, 3180, 1889, 5542, 1695, 9557, 1437,  930, 8707])

In [208]:
b_temp = np.array([b[i] for i in d]).argsort()
b_temp.argsort()
d = d[b_temp.argsort()]
d

array([1, 4, 9])

In [209]:
b

array([2268, 6562, 4903, 4358, 7054, 2160, 8346, 1476, 1234, 7451])

In [210]:
Sa

array([      5,       3,       1,      -3,      -2,       2,       3,
             1, -100001,      -8])

In [211]:
Sb

array([      5,       1,       1,      -3,      -3,       2,       3,
             1, -100001,      -5])

In [174]:
l = []
weight = 0
for i in a.argsort():
    if i in d:
        l.append(weight)
        weight = 0
    if Sa[i] == Sb[i]:
        weight += 1
l.append(weight)
l

[1, 0, 2, 4]

In [175]:
weight

4

In [176]:
d

array([7, 2, 5])

In [41]:
d = d[b_temp.argsort()]

In [42]:
d

array([6, 8, 2])

In [29]:
d = d[b_temp.argsort()]

In [33]:
b.

array([     5,      3,      4,     -3,     -2,      2, 100001,      1,
            1,     -8])

In [32]:
a

array([     5,      3,      1,     -3,     -2,      2,      3,      1,
       100001,     -8])